### ISSUE TITLE
Memory issue for longer tests

### ISSUE THREAD

**Issue by markgandy** [shoreditch-ops/artillery#130] opened 2016-07-11 05:56 UTC
We are seeing an issue with artillery running out of memory for longer tests - memory gradually increases until it hits limit, then CPU spikes and the test crashes. I don't know if there is a memory leak somewhere - we are running tests up to around 30 requests per second. Artillery is running in a docker container (with 1GB of memory allocated) on a t2.small in AWS.

Config has multiple phases:

```
  phases:
    - duration: 300
      arrivalRate: 10
    - duration: 300
      arrivalRate: 12
    - duration: 300
      arrivalRate: 14
    - duration: 300
      arrivalRate: 16
    - duration: 300
      arrivalRate: 18
    - duration: 300
      arrivalRate: 20
    - duration: 300
      arrivalRate: 22
    - duration: 300
      arrivalRate: 24
    - duration: 300
      arrivalRate: 26
    - duration: 300
      arrivalRate: 28
    - duration: 300
      arrivalRate: 30
```

with each scenario just calling a single GET request

**Comment by hassy** [comment] 2016-07-11 09:11
Very interesting and will hopefully be easy to reproduce if the scenario is that simple.

Are you using CSV payloads to make requests or is it always the same request? If you are, how large is the file (# of rows and columns and size in bytes)?

What sort of a response does the server send? (content type, content length)

Thanks @markgandy , I will try to reproduce!

**Comment by markgandy** [comment] 2016-07-11 23:46
Yeah, sorry forgot to mention @hassy we are using a CSV payload. It is 50 lines and just has a single UUID per line.

This is a typical response from the server (Content-Type is application/json):

```
{
  "contents": [
    {
      "contentId": "cd063351-2749-4bff-8b8a-ea9491fb64ac",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "Cereal offer",
      "contentType": "app",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [],
      "videos": [],
      "publish": "2016-07-04T15:43:08.000Z",
      "expire": null,
      "presentMode": 2,
      "segments": [],
      "availability": "any",
      "tags": [],
      "isListed": true,
      "created": "2016-07-04T05:43:19.879Z",
      "modified": "2016-07-04T05:43:19.889Z"
    },
    {
      "contentId": "5e221b74-90bf-4b08-848b-aa8ed476e9fc",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "bfhsfbsdh",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "shortDescription": "fjsdbfj",
      "contentType": "app",
      "discount": "xx",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [],
      "videos": [],
      "publish": "2016-07-06T14:03:25.000Z",
      "expire": "2016-07-22T17:00:00.000Z",
      "presentMode": 1,
      "segments": [],
      "availability": "any",
      "tags": [],
      "isListed": true,
      "created": "2016-07-06T04:04:39.860Z",
      "modified": "2016-07-06T04:04:39.868Z"
    },
    {
      "contentId": "7129b701-36b6-4f41-88c5-376157414ce0",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "fnsjfnsj",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "shortDescription": "nfsdjnj",
      "contentType": "app",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [],
      "videos": [],
      "publish": "2016-07-06T14:04:58.000Z",
      "expire": null,
      "presentMode": 1,
      "segments": [],
      "availability": "any",
      "tags": [],
      "isListed": true,
      "created": "2016-07-06T04:05:12.400Z",
      "modified": "2016-07-06T04:05:12.405Z",
      "attributes": [
        {
          "key": "key",
          "value": "value"
        },
        {
          "key": "key2",
          "value": "value2"
        }
      ]
    },
    {
      "contentId": "1a7dc001-347d-4841-a95a-93b0e251a43a",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "fasnfjhwse",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "shortDescription": "dbashdbh",
      "contentType": "app",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [],
      "videos": [],
      "publish": "2016-07-06T14:05:14.000Z",
      "expire": null,
      "presentMode": 1,
      "segments": [],
      "availability": "any",
      "tags": [],
      "isListed": true,
      "created": "2016-07-06T04:05:42.141Z",
      "modified": "2016-07-06T04:05:42.145Z",
      "attributes": [
        {
          "key": "hbfsdgvg",
          "value": "jefbnewhj"
        },
        {
          "key": "ufgsdfbhsfb",
          "value": "hbgsdhsed"
        },
        {
          "key": "fbsfdsdsfy",
          "value": "nfgjsdbgf"
        },
        {
          "key": "ufhsdbf",
          "value": "ubfgsdh"
        }
      ]
    },
    {
      "contentId": "5350ee59-8511-4f29-93de-e7d778d83185",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "fubnsb",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "shortDescription": "bnfdhsdfb",
      "contentType": "app",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [],
      "videos": [],
      "publish": "2016-07-06T14:05:44.000Z",
      "expire": null,
      "pushMsg": "hfjbsdhfjbsd",
      "presentMode": 2,
      "segments": [],
      "availability": "any",
      "tags": [],
      "isListed": false,
      "created": "2016-07-06T04:06:03.668Z",
      "modified": "2016-07-06T04:06:03.671Z"
    },
    {
      "contentId": "1eb4e812-702f-48cf-9589-96f9a155a6c8",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "hsefbehwy",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "shortDescription": "nfweubfw",
      "contentType": "app",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [],
      "videos": [],
      "publish": "2016-07-06T14:06:29.000Z",
      "expire": null,
      "presentMode": 1,
      "segments": [],
      "availability": "any",
      "tags": [
        {
          "_id": "2jirjn2A",
          "tagId": "2jirjn2A",
          "tagName": "tag1",
          "fullTagName": "tag1",
          "showInList": true
        }
      ],
      "isListed": true,
      "created": "2016-07-06T04:07:02.901Z",
      "modified": "2016-07-06T04:07:02.910Z",
      "related": [
        {
          "contentId": "cd063351-2749-4bff-8b8a-ea9491fb64ac",
          "attributes": []
        },
        {
          "contentId": "7129b701-36b6-4f41-88c5-376157414ce0",
          "attributes": []
        }
      ]
    },
    {
      "contentId": "0451d1e0-96da-4195-887d-c0b759e28d6c",
      "projectId": "8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000",
      "title": "nfsjafbs",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "shortDescription": "nfsfbhsd",
      "contentType": "app",
      "price": "200",
      "categories": [],
      "spots": [],
      "urls": [],
      "images": [
        {
          "url": "https://s3-ap-southeast-2.amazonaws.com/spotz.images/dev/retail/projects/8JCv5UiH0F50Dq2rW9UBWdwKnI10EOQErANu6000/images/t1larg.cereal.ward.off.hypertension.jpg"
        }
      ],
      "videos": [],
      "publish": "2016-07-06T14:07:06.000Z",
      "expire": null,
      "presentMode": 2,
      "segments": [],
      "availability": "any",
      "tags": [],
      "isListed": true,
      "created": "2016-07-06T04:08:31.988Z",
      "modified": "2016-07-06T05:24:46.365Z"
    }
  ],
  "screenzSpotIds": []
}
```

**Comment by hassy** [comment] 2016-07-12 09:19
Thanks @markgandy, looks like it should be pretty straightforward to reproduce.

**Comment by hassy** [comment] 2016-09-29 14:55
I haven't been able to reproduce this. Are you still seeing this issue @markgandy?

**Comment by hassy** [comment] 2016-09-29 15:10
@markgandy Do you have anything else memory-heavy running alongside Artillery? The way stats are aggregated **does** cause memory growth over the lifetime of an Artillery process, but you shouldn't be anywhere near 1GB after 55m at ~30 RPS.

**Comment by hassy** [comment] 2016-11-24 13:49
Closing for now - unable to reproduce.

**Comment by dteirney** [comment] 2016-12-06 00:17
We've run into a number of problems with artillery running out of memory lately as well. Long soak tests explode eventually, and very short tests with large API responses also explode. We're using the statsd plugin but otherwise everything is vanilla artillery.

What information would be useful to help diagnose this problem?

**Comment by hassy** [comment] 2016-12-06 09:54
@dteirney Interesting, thanks for getting in touch about this!

Which versions of Node.js and Artillery are you on? Does Artillery fail with a memory allocation error (i.e. V8 reaches the maximum memory limit) or do you run Artillery in a memory constrained environment such as a small EC2 instance and it's getting killed by the OS?

What would be most helpful is an isolated example. I appreciate those can take a long time to produce though. To start with, I think exploring short tests with large API responses offers the most promise. To try to isolate the problem, it would be useful to know:

1. How large are those responses on average?
2. What does the `phases` part of the test look like?
3. How many requests that result in a large response does the average virtual user make?
4. Are you using captures or transforms on any of the responses?

**Comment by dteirney** [comment] 2016-12-06 10:49
@hassy you can see the YAML configuration for one of the problematic artillery scripts at https://github.com/orionhealth/apigee-edgemicro-testing/blob/master/templates/artillery/stream-test.yaml

I'm using Node 7.2.0 and artillery 1.5.0-17. Artillery fails with a memory allocation error. I've had to bump up the heap size for V8 to get some scripts to run without exploding using:

```node --max_old_space_size=3072 `which artillery` run -e edgemicro stream-test.yaml```

I'm pretty sure that covers answers to questions 1 through 4. The sizes of the response are obvious from the requests in the configuration.

**Comment by hassy** [comment] 2016-12-06 11:04
Perfect, thanks @dteirney

**Comment by dteirney** [comment] 2016-12-21 19:16
@hassy is there anything else I can provide to help diagnose this memory issue? I've had to increase the heap size up to 8GB to run a 5-minute test.

**Comment by hassy** [comment] 2016-12-26 15:47
@dteirney nothing more needed for now, thanks. I'm pretty sure we've narrowed the cause of the issue, it's just a matter of shipping fixes now.

**Comment by dteirney** [comment] 2016-12-28 07:02
@hassy good to know the issue has been found. Do you know what the timeframe might be for shipping the fixes?

**Comment by hassy** [comment] 2017-01-05 16:52
@dteirney a fix is on its way

**Comment by hassy** [comment] 2017-01-05 17:14
@dteirney can you try `v1.5.0-21` and see if that provides an improvement?

**Comment by hassy** [comment] 2017-01-10 11:55
Closing for now, will reopen if the problem is reported again.

**Closed by hassy** 2017-01-10 11:55 UTC
Labels: bug, investigate

**Comment by dteirney** [comment] 2017-01-16 03:53
@hassy just run some of our tests with the new 1.5 release and no problems so far. Thanks!

**Comment by benlipp** [comment] 2017-05-23 23:25
@hassy I'm having issues with memory leaks on 1.6.0-2.

**Comment by hassy** [comment] 2017-05-24 04:37
@benlipp Thanks. Do you have an example to demonstrate?

**Comment by benlipp** [comment] 2017-05-24 18:32
Do you want our configs? All I know is that we had three instances of artillery running on a machine with 16GB of RAM, and two of them ran out of memory. I was watching memory usage in htop, and it was steadily climbing until it died.

**Comment by benlipp** [comment] 2017-05-24 18:50
The first one died with this:
```
<--- Last few GCs --->

  500054 ms: Mark-sweep 1395.3 (1458.0) -> 1395.1 (1458.0) MB, 1883.6 / 1 ms [allocation failure] [GC in old space requested].
  501995 ms: Mark-sweep 1395.1 (1458.0) -> 1395.1 (1458.0) MB, 1941.6 / 1 ms [allocation failure] [GC in old space requested].
  503980 ms: Mark-sweep 1395.1 (1458.0) -> 1395.1 (1458.0) MB, 1984.1 / 1 ms [last resort gc].
  505957 ms: Mark-sweep 1395.1 (1458.0) -> 1394.9 (1458.0) MB, 1977.3 / 1 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x34d1d7cb4629 <JS Object>
    1: new constructor(aka XMLHttpRequest) [/usr/local/lib/node_modules/artillery/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:~37] [pc=0x2b50c82dc1bd] (this=0x1465c70449a1 <an XMLHttpRequest with map 0xec7ed013829>,opts=0x1465c7044911 <an Object with map 0xec7ed00b7f1>)
    3: create [/usr/local/lib/node_modules/artillery/node_modules/engine.io-client/lib/transports/polling-xhr.js:193...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
 -Unexpected error, Artillery shutting down.
```

and the second one died with:

```
<--- Last few GCs --->

  518250 ms: Scavenge 1400.4 (1458.0) -> 1400.4 (1458.0) MB, 17.9 / 0 ms (+ 10.1 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  520113 ms: Mark-sweep 1400.4 (1458.0) -> 1398.3 (1458.0) MB, 1862.9 / 1 ms (+ 160.9 ms in 668 steps since start of marking, biggest step 10.1 ms) [last resort gc].
  521898 ms: Mark-sweep 1398.3 (1458.0) -> 1398.6 (1458.0) MB, 1784.8 / 1 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3f06471b4629 <JS Object>
    1: doPoll [/usr/local/lib/node_modules/artillery/node_modules/engine.io-client/lib/transports/polling-xhr.js:~121] [pc=0x2679985d550e] (this=0x3f06471c4f29 <an XHR with map 0x3b8e69d0a7c9>)
    2: open [/usr/local/lib/node_modules/artillery/node_modules/engine.io-client/lib/transport.js:~77] [pc=0x267998ed5fd0] (this=0x3f06471c4f29 <an XHR with map 0x3b8e69d0a7c9>)
    3: open [/usr/local/l...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
 -Unexpected error, Artillery shutting down.

```
Here are the phases we're using:

```
"phases": [
            { "duration": 60, "arrivalRate": 5, "name": "PHASE I: the warm-up" },
            { "duration": 180, "arrivalRate": 15, "name": "PHASE II: low stress" },
            { "duration": 180, "arrivalRate": 50, "name": "PHASE III: high stress" },
            { "duration": 180, "arrivalRate": 150, "name": "PHASE IV: insane" }
        ]
    },
```

**Comment by hassy** [comment] 2017-05-24 19:48
Thanks @benlipp. An Artillery test script that would reliably reproduce the problem would be ideal. As it stands it's hard to tell what the problem is as memory growth does not necessarily mean there's a memory leak. You could have a lot of concurrent virtual users for example, exchanging a lot of data with the server which could cause high memory usage. In your particular example the last phase alone creates 27,000 virtual users. Maybe you need to run Node.js with an increased memory limit to be able to run your tests, it's impossible to say without knowing what your tests are doing. Are you able to run the same tests on an earlier version of Artillery without seeing the same problem?

**Comment by benlipp** [comment] 2017-05-24 19:53
>An Artillery test script that would reliably reproduce the problem would be ideal. 

https://gist.github.com/benlipp/7ca805a4f3dfe4e3bbe2b392332ef213

>Maybe you need to run Node.js with an increased memory limit to be able to run your tests, it's impossible to say without knowing what your tests are doing.

How would I do this? Running on Ubuntu 16.04

> Are you able to run the same tests on an earlier version of Artillery without seeing the same problem?

I'm not sure, I haven't tried an earlier version. How would I do that?
