### ISSUE TITLE
Sending JSON in Websocket tests

### ISSUE THREAD

**Issue by phantomvivek** [shoreditch-ops/artillery#552] opened 2018-10-11 07:14 UTC
Hello,

We have been using artillery for our ws load tests and we are running into some issues on how to setup the tests, specifically with sending JSONs in the **send** parameter. If we want to use payload files instead of hardcoded JSON strings, this does not quite seem to work. Below is the JSON config that we're using:

```
{
	"config":
	{
		"target": "ws://IP:PORT",
		"phases": [
		{
			"duration": 10,
			"arrivalRate": 1,
			"rampTo": 10
		}],
		"ws":{ "rejectUnauthorized": false }
	},
	"scenarios": [
	{
		"engine": "ws",
		"flow": [
		{
			"send": "{\"id\":1,\"sessionId\":\"**sessionId**\"}"
		}]
	}]
}

```
So I wanted to know a couple of things:
1. How do we use the JSON attribute inside the send attribute?
2. If I needed to attach values to keys inside this JSON through a CSV, how do we do this?

**Comment by hassy** [comment] 2018-10-11 10:46
`send` sends the data as a string, and it's up to the server how it wants to deserialize it (by parsing it as JSON for example). Do you have an example script that uses an external CSV file that isn't working?

**Comment by phantomvivek** [comment] 2018-10-11 11:01
We do deserialization on the server, and the script below seems to work partially in that it sends the JSON as {id: 1, sessionId: ''} (this is string deserialized by the server, so that's cool) but the parameters are not replaced from the CSV:

```
{
	"config":
	{
		"target": "ws://IP:PORT",
		"phases": [
		{
			"duration": 60,
			"arrivalRate": 1,
			"rampTo": 20,
			"name": "Warm up"
		}],
		"ws": [
		{
			"rejectUnauthorized": false
		}],
		"payload":
		{
			"path": "sessions.csv",
			"fields": "sessionId"
		}
	},
	"scenarios": [
	{
		"engine": "ws",
		"flow": [
		{
			"send":
			{
				"id": "1",
				"sessionId": "{{ sessionId }}"
			}
		}]
	}]
}
```

The CSV file:
```
sessionId
abc
pqr
def
```

**Comment by hassy** [comment] 2018-10-25 09:30
I'm unable to reproduce the issue with the latest version of Artillery (`v1.6.0-24`). What version of Artillery are you using @phantomvivek?

**Comment by hassy** [comment] 2018-11-22 15:17
Closing for now, feel free to re-open with more info.

**Closed by hassy** 2018-11-22 15:17 UTC
Labels: need-more-info
