### ISSUE TITLE
Feature: Route reports - log of routes and times

### ISSUE THREAD

**Issue by eshinFG** [shoreditch-ops/artillery#231] opened 2016-12-13 17:58 UTC
Thank you for creating this stress test tool! 

Would be great if I could see which route/s is taking the longest where. 

Log of times and routes and other useful data in a report form.

Thank you!

**Comment by hassy** [comment] 2016-12-13 18:05
Definitely a useful feature that should be built in. 👍 

In the meantime this can be accomplished with a little bit of custom JS:

```yaml
- post:
    url: "/some/resource"
    json:
     some: "data"
    name: "Name the route for reports"
    beforeRequest: ["recordStartTime"]
    afterResponse: ["reportLatency"]
```

```javascript
function recordStartTime(req, context, events, done) {
  context.vars._startTime = Date.now();
  return done();
}

function reportLatency(req, res, context, events, done) {
  if (context.vars._startTime) {
    var delta = Date.now() - context.vars._startTime;
    events.emit('customStat', { stat: `latency for ${req.name || req.url}`, value: delta });
  }
  return done();
}
```

Untested, but should work.

**Comment by eshinFG** [comment] 2016-12-13 22:18
Thank you so much hassy! It worked like a charm. Great stuff!

**Comment by eshinFG** [comment] 2016-12-15 19:54
Heres my code I am using to find averages.
```
var alltimes = 0
var count = 0;
var obj = {};

function recordStartTime(req, context, events, done) {
    context.vars._startTime = Date.now();
```

```
    if (obj[req.name] === undefined) {
        obj[req.name] = {};
        obj[req.name].count = 0;
        obj[req.name].alltimes = 0;
    }

    return done();
}
```
```
function reportLatency(req, res, context, events, done) {

    if (context.vars._startTime) {
        var delta = Date.now() - context.vars._startTime;
        // console.log(delta)
        obj[req.name].count++;
        obj[req.name].alltimes += delta;
        var averageTime = obj[req.name].alltimes / obj[req.name].count;
        obj[req.name].averageTimes = averageTime;
        if (obj[req.name].count === 10) { //Here i'd like insert a value for arrivalRate * duration
            console.log(" ")  
            console.log("****** Names            - ", req.name)
            console.log("****** Average Time     - ", obj[req.name].averageTimes)
            console.log("****** Count            - ", obj[req.name].count)
        }
        events.emit('customStat', { stat: `latency for ${req.name || req.url}`, value: delta });
    }
    return done();
}
```
```
module.exports = {
    recordStartTime: recordStartTime,
    reportLatency: reportLatency
}
```

**Comment by tiffanywilson** [comment] 2016-12-19 22:19
@hassy this is awesome!

**Comment by soumsg** [comment] 2017-01-11 11:20
This is great Hassy!!

**Comment by dustinsmith1024** [comment] 2018-07-26 20:51
Thanks for this - looks like there is a TODO to deprecate the `customStat` event. So you might want to use `histogram` instead, which takes to function args instead of an object.

```js
ee.emit('histogram', `latency for ${req.uri}`, req.totalTimeInSeconds);
```

**Comment by hassy** [comment] 2018-11-28 17:10
Duplicate of #92

**Closed by hassy** 2018-11-28 17:10 UTC
Labels: engine:http, enhancement

**Comment by Ellesedil** [comment] 2019-05-01 17:28
> Thanks for this - looks like there is a TODO to deprecate the `customStat` event. So you might want to use `histogram` instead, which takes to function args instead of an object.
> 
> ```js
> ee.emit('histogram', `latency for ${req.uri}`, req.totalTimeInSeconds);
> ```

Does this mean that the `recordStartTime` method is unnecessary? Looks like the request object has everything it needs to report the elapsed time of each endpoint request, right?

**Comment by eliezercazares** [comment] 2022-06-21 21:42
console.log does not seem to be embedded into the report anymore? 
I am using socket.io engine v3. 
I need to output some values to the .json report
