### ISSUE TITLE
Artillery gives ETIMEOUT and ESOCKETTIMEOUT, though the server runs perfectly. Also, there is a mismatch in number of scenarios launched and ETIMEOUTs received in the artillery output.

### ISSUE THREAD

**Issue by cskru** [shoreditch-ops/artillery#436] opened 2018-03-07 05:00 UTC
**yml:**
```yml
config:
  payload:
    path: "file.csv"
    fields:
      - "name"
    order: "sequence"
  target: 'http://localhost:8000'
  phases:
    - duration: 1
      arrivalCount: 30
scenarios:
  - flow:
    - get:
        url: "/path/{{ name }}"

```
**Output:**
```
all scenarios completed
Complete report @ 2018-03-07T04:03:38.796Z
  Scenarios launched:  30
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: 0.24
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 30 (100%)
  Errors:
    ETIMEDOUT: 58
    ESOCKETTIMEDOUT: 4
```
Why are the numbers out of sync?
I have sent 30 requests. But ETIMEOUT is 58 and ESOCKETTIMEOUT is 4.
What do they mean?

Also, **I cannot see any anomaly in my server. It accepts 30 requests and runs perfectly.**
In between, artillery stops, giving this message.
Any help is much appreciated.

**Comment by hassy** [comment] 2018-03-07 10:14
A reproducible case would be great. Otherwise there's nothing to go on. The numbers *should* agree, but it's impossible to even start looking at what the issue might be without a reproducible test case.

**Comment by cskru** [comment] 2018-03-08 06:28
@hassy , this issue of timeouts got resolved when I introduced config.http.timeout.
Still, even if I dont introduce this config, numbers should be in sync.

Today, I observed another issue of mismatching numbers.
Example Repo for you to reproduce the issue: https://github.com/cskru/artillery_experiment
* Clone this
* Do ```npm install```
* Do ```npm run example``` , observed the results.
* Do ```artillery run ./test/example.yml``` and observe the results.

**Issue is:** 
When I launch the test using the npm command I've constructed, numbers' mismatch can be seen.
When I launch the test using the command : ```artillery run example.yml```, it works kinda fine.

Which is strange :)

More details:
When I run this test with the npm command I've constructed, I'll get mismatch in the numbers:
Observe 83 in the output.
Output:
```all scenarios completed
Complete report @ 2018-03-08T06:14:48.102Z
  Scenarios launched:  83
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: 32.68
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 83 (100%)
  Errors:
    ECONNREFUSED: 83
    connect ECONNREFUSED 127.0.0.1:8000: 83
```
When I run the same by giving the command directly, it works fine. (artillery run example.yml)
Output:
```Summary report @ 11:46:29(+0530) 2018-03-08
  Scenarios launched:  80
  Scenarios completed: 0
  Requests completed:  0
  Concurrent users:    81
  RPS sent: 31.87
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    0: 80 (100%)
  Errors:
    ECONNREFUSED: 80
```
I've not started the server here, so it's fine to get ECONNREFUSED.
I am concerned with the numbers. :)

**Comment by hassy** [comment] 2018-03-08 14:01
That's great, thanks @cskru! We'll look into it.

**Comment by fhnstephen** [comment] 2018-03-22 04:15
We have similar issue here.

When we try to send ~6000 requests in 300seconds, it sent more than that.

Is there any progress about this issue?

**Comment by hassy** [comment] 2018-03-24 17:30
@cskru your issue most likely has to do with the version of Artillery that gets installed with `*` as the version string in your package.json. The latest version of Artillery is working fine.

@fhnstephen there's no issue with the most recent version of Artillery as far as we can tell right now. More information to help reproduce any possible issues you're seeing would be great.

**Comment by tiffanywilson** [comment] 2018-05-25 16:45
@fhnstephen @cskru @hassy We have run into similar issues when running locally. Basically the timeouts occur because our laptops are not powerful enough to handle the higher amounts of load. We've solved this by setting the tests up to run through AWS Lambdas.

**Comment by hassy** [comment] 2018-05-25 17:02
Thanks @tiffanywilson, it's always a good idea to run real tests from the cloud somewhere.

Closing this as the originally reported issue is most likely to do with an outdated version of Artillery used.

**Closed by hassy** 2018-05-25 17:02 UTC
Labels: need-more-info
